### ISSUE TITLE
IDE stops resolving symbols from clojure core library

### ISSUE THREAD

**Issue by jitlogic** [cursive-ide/cursive#2173]
There are random occurences when Cursive stops resolving symbols from clojure core library. Project has two clojure dependencies: [org.clojure/clojure "1.10.0"] for Clojure and [org.clojure/clojurescript "1.10.238"] (:provided profile). Plugin version: v1.8.2-eap2-2019.1.

**Comment by jitlogic** [comment]
After restarting IDE symbols resolving somtimes starts working again. Sometimes just changing anything in code editor helps. For me there is no apparent rule when resolving mechanism stops working or how to make it running back again.

**Comment by cursive-ide** [comment]
Yes, this is a problem after upgrading to IntelliJ 2019.1. Something seems to have changed in the base platform which is either exposing a bug in Cursive or provoking some kind of problem. It's being tracked in [IDEA-211736](https://youtrack.jetbrains.com/issue/IDEA-211736).

**Comment by JJ-Atkinson** [comment]
If it's helpful, I've noticed this issue 5 times in a row after creating a quil sketch (`lein new quil hello-quil`) consistently. Currently 5/6 times it has failed on a fresh project.

**Comment by cursive-ide** [comment]
@JJ-Atkinson That does sound helpful, thanks - I'll try to reproduce with that. Do you have other projects open at the same time?

**Comment by JJ-Atkinson** [comment]
@cursive-ide  Yes, I did.

**Comment by cursive-ide** [comment]
As an update, I'm working with JetBrains on this, and we've made some progress in being able to reproduce it.

**Comment by cursive-ide** [comment]
This has been confirmed as a problem in the IntelliJ platform, and should be fixed soon. It will definitely be fixed in 2019.2, and will probably be backported to a 2019.1 release as well.

**Comment by jrasanen** [comment]
Would anyone know if IDEA has released a backported fix yet?

**Comment by cursive-ide** [comment]
No, sadly, they're still working on a fix. They have said they'll have it ready before the 2019.2 release, but that's getting very close now for a fix of this magnitude - we'll see.

**Comment by Dirklectisch** [comment]
Is there a known workaround for this problem?

**Comment by cursive-ide** [comment]
@Dirklectisch A short-term workaround is just to restart the IDE when it happens, which sometimes works. Sadly, the definitive workaround is to downgrade to IntelliJ 2018.3.

**Comment by jrasanen** [comment]
I suppose upgrading to the unstable version could solve this too eventually? They've just recently released [IDEA 2019.2 Beta2](https://blog.jetbrains.com/idea/2019/07/intellij-idea-2019-2-beta2-is-out/).

**Comment by cursive-ide** [comment]
@jrasanen Yes, they're getting scarily close to a final release now, and there's still no fix for this been committed as far as I can tell (and I confirmed a couple of days ago with the developer). Fingers crossed! If it doesn't make the first 2019.2 release, I guess it will make it into a later point release.

**Comment by Dirklectisch** [comment]
For me no amount of restarting or recreating a new project could get IntelliJ to recognise the core symbols. So what I did is copy over an existing working project and strip it down. So that's another possible work around.

**Comment by cursive-ide** [comment]
I've been speaking to JetBrains about this. They have a fix implemented, but it will not make it in in time for 2019.2. It's a fix to a complicated and intermittent problem in a critical part of their infrastructure, so they have to be careful with it. It will be in 2019.2.1 - I'm not sure when that will be out, but it should be within a week or two of the main release.

**Comment by gorakhargosh** [comment]
Has this been fixed? I have a project in which IntelliJ just stopped identifying symbols.
IntelliJ  IDEA 2019.3

**Comment by cursive-ide** [comment]
@gorakhargosh Yes, this has been fixed, I'll close this issue. For your issue, does _File | Invalidate Caches & Restart..._ help?

**Comment by gorakhargosh** [comment]
Hi @cursive-ide that didn't help. Still get a lot of unresolved symbols.

**Comment by cursive-ide** [comment]
@gorakhargosh Which symbols are you seeing undefined? Two common things to check are that the libraries (including Clojure) are correctly attached to your module, see _File | Project Structure | Modules | <your module> | Dependencies_.

**Comment by kiramclean** [comment]
I just experienced this, too. Uninstalling and re-installing seems to have worked.

**Comment by jcjolley** [comment]
I'm still experiencing this issue on 2020.2.2
![image](https://user-images.githubusercontent.com/2086176/93392303-ccb74100-f82d-11ea-8a25-0e03ee7fc115.png)

![image](https://user-images.githubusercontent.com/2086176/93392373-e9537900-f82d-11ea-9dcc-cc6c0633819a.png)

It was working fine yesterday, then today, no clojure symbols will resolve.

**Comment by cursive-ide** [comment]
@jcjolley Does any of this help? https://cursive-ide.com/userguide/eap/troubleshooting.html#help-lots-of-symbols-don-t-resolve

**Comment by skrypka** [comment]
I had similar problem - spend one hour trying to resolve. In my case somehow in Clojure Deps/Aliases `test (system)` become selected instead of `dev`.
