### ISSUE TITLE
Test exceptions/errors not printed in the REPL

### ISSUE THREAD

**Issue by rutchkiwi** [cursive-ide/cursive#2950]
I'm not sure in which version this was introduced, but can't have been more than 4 months ago. Since then, when a test crashes, the stack trace/error is not printed to the REPL. This is really annoying as I can't easily see or navigate to where the error happened like before. Clicking "print last exception" doesn't help either.
I'm not sure if this is a bug or an intended behaviour, but if the latter, I'd really like the capacity to turn it off.

<img width="1437" alt="Screenshot 2024-08-23 at 14 45 33" src="https://github.com/user-attachments/assets/f5913131-d886-4a5c-82a8-cf6e8dc984fa">

**Comment by cursive-ide** [comment]
I see, I'll try to repro this, thanks. The exceptions are usually shown inline now, but I think the issue is the "not in assertion" bit. I'll check this.

**Comment by cursive-ide** [comment]
Yes, as expected this was a bug in exceptions outside assertions. It's fixed for the next build.

<img width="483" alt="Screenshot 2024-08-28 at 17 19 48" src="https://github.com/user-attachments/assets/8c0a501b-0a9e-40a7-81f0-d9568529aa7f">

**Comment by rutchkiwi** [comment]
That was fast, thanks! :)

Is there an option to show the exceptions in the REPL as before? Having them be always visible and the stack trace lines clickable is quite handy

**Comment by cursive-ide** [comment]
Not currently, but this whole area is still under ongoing work. The stack trace will be interactive in the editor shortly, which will allow navigation, and it will also remain there as long as you leave it and can always be opened up again if you accidentally close it. I'd like to leave it as is for a while, and after all the changes are in if it's too annoying then I'll look at printing in the output.

**Comment by rutchkiwi** [comment]
ok!
To clarify why I want the exception in the REPL and not inline - an exception being thrown in my tests indicate not that a specific assertion has called, but rather that something in the setup of the test has crashed - so all the remaining tests are no longer valid. (at least like 90% of the time)

**Comment by cursive-ide** [comment]
Fix released in 1.14.0-eap1 on 2024-09-13.

**Comment by rutchkiwi** [comment]
Can confirm the stack traces are clickable now, thanks! :)
However, they're still not clickable, which makes my workflow still quite painful. Is that intended behaviour? Happy to create another issue if you'd rather

**Comment by cursive-ide** [comment]
Sorry, can you clarify? You say they're clickable, but then that they're not.

**Comment by rutchkiwi** [comment]
Sorry, I mistyped. I meant to say the traces are *visible* now, but not clickable. They can be highlighted but clicking or pressing enter with them selected doesn't take you to the corresponding code. So I have to memorise the file and line, then navigate there manually.
